/* ══════════════════════════════════════════════════════════════════════════
   TEST AUDIO — synthesised, not sampled
   ══════════════════════════════════════════════════════════════════════════

   Every sound here is generated by the Web Audio API at runtime. Nothing is
   downloaded and nothing is licensed, which sidesteps the whole question of
   rights over "royalty-free" loops — you cannot infringe a waveform you
   computed yourself.

   The background bed is a slow pentatonic pad. Pentatonic because no two notes
   in it can clash, so an endless random walk never produces a sour interval;
   slow because the point is concentration, not entertainment. It sits about
   18 dB under the effects and ducks whenever a question is being spoken.
   ══════════════════════════════════════════════════════════════════════════ */

let ctx: AudioContext | null = null

function audio(): AudioContext | null {
  if (typeof window === 'undefined') return null
  if (!ctx) {
    const AC = window.AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext
    if (!AC) return null
    ctx = new AC()
  }
  // Browsers suspend the context until a gesture; resume is a no-op if running.
  if (ctx.state === 'suspended') void ctx.resume()
  return ctx
}

/** Call once from a click handler so later sounds are allowed to play. */
export function unlockAudio(): void { audio() }

/* ── Effects ────────────────────────────────────────────────────────────── */

type Note = { f: number; t: number; d: number; type?: OscillatorType; gain?: number }

function play(notes: Note[], master = 0.18) {
  const c = audio()
  if (!c) return
  const bus = c.createGain()
  bus.gain.value = master
  bus.connect(c.destination)

  for (const n of notes) {
    const osc = c.createOscillator()
    const g = c.createGain()
    osc.type = n.type ?? 'sine'
    osc.frequency.setValueAtTime(n.f, c.currentTime + n.t)
    // a short attack and an exponential tail — square edges click audibly
    g.gain.setValueAtTime(0.0001, c.currentTime + n.t)
    g.gain.exponentialRampToValueAtTime(n.gain ?? 1, c.currentTime + n.t + 0.012)
    g.gain.exponentialRampToValueAtTime(0.0001, c.currentTime + n.t + n.d)
    osc.connect(g); g.connect(bus)
    osc.start(c.currentTime + n.t)
    osc.stop(c.currentTime + n.t + n.d + 0.02)
  }
}

/** Rising major third — the shape of "yes". */
export function sfxCorrect() {
  play([
    { f: 587.33, t: 0,     d: 0.16 },              // D5
    { f: 739.99, t: 0.075, d: 0.18 },              // F#5
    { f: 987.77, t: 0.15,  d: 0.34, gain: 0.75 },  // B5
  ])
}

/** Falling semitone on a soft saw — wrong, but not a buzzer. */
export function sfxWrong() {
  play([
    { f: 261.63, t: 0,    d: 0.20, type: 'triangle' },
    { f: 233.08, t: 0.09, d: 0.30, type: 'triangle', gain: 0.8 },
  ], 0.14)
}

/** A heart just went. Low, short, unmistakable. */
export function sfxHeartLost() {
  play([
    { f: 174.61, t: 0,    d: 0.22, type: 'sine' },
    { f: 130.81, t: 0.11, d: 0.34, type: 'sine', gain: 0.7 },
  ], 0.16)
}

/** Level cleared — an arpeggio that keeps climbing. */
export function sfxLevelUp() {
  play([
    { f: 523.25, t: 0,    d: 0.16 },
    { f: 659.25, t: 0.09, d: 0.16 },
    { f: 783.99, t: 0.18, d: 0.16 },
    { f: 1046.5, t: 0.27, d: 0.42, gain: 0.8 },
  ], 0.2)
}

/** A heart earned on entering a harder level. */
export function sfxHeartGained() {
  play([
    { f: 659.25, t: 0,    d: 0.14 },
    { f: 880.00, t: 0.08, d: 0.26, gain: 0.8 },
  ], 0.16)
}

/** End of the test. */
export function sfxFinish() {
  play([
    { f: 523.25, t: 0,    d: 0.20 },
    { f: 659.25, t: 0.12, d: 0.20 },
    { f: 783.99, t: 0.24, d: 0.20 },
    { f: 1046.5, t: 0.36, d: 0.20 },
    { f: 1318.5, t: 0.48, d: 0.60, gain: 0.7 },
  ], 0.2)
}

/* ── Ambient bed ────────────────────────────────────────────────────────── */

/** A minor pentatonic across two octaves — no interval in it can clash. */
const SCALE = [220.00, 261.63, 293.66, 349.23, 392.00, 440.00, 523.25, 587.33, 698.46]

let bed: {
  master: GainNode
  timer: number
  stopped: boolean
} | null = null

/**
 * Start the background pad. Idempotent — calling it twice does nothing.
 * Must be triggered by a user gesture or the browser will refuse.
 */
export function startMusic(volume = 0.055): void {
  const c = audio()
  if (!c || bed) return

  const master = c.createGain()
  master.gain.setValueAtTime(0.0001, c.currentTime)
  master.gain.exponentialRampToValueAtTime(volume, c.currentTime + 3)

  // a gentle low-pass keeps it behind the voice rather than beside it
  const filter = c.createBiquadFilter()
  filter.type = 'lowpass'
  filter.frequency.value = 1100
  filter.Q.value = 0.4

  master.connect(filter)
  filter.connect(c.destination)

  const state = { master, timer: 0, stopped: false }
  bed = state

  /** One long, soft note. Two detuned oscillators give it body. */
  function voice(freq: number, dur: number) {
    const cc = audio()
    if (!cc || state.stopped) return
    const g = cc.createGain()
    g.gain.setValueAtTime(0.0001, cc.currentTime)
    g.gain.exponentialRampToValueAtTime(0.5, cc.currentTime + dur * 0.35)
    g.gain.exponentialRampToValueAtTime(0.0001, cc.currentTime + dur)
    g.connect(state.master)

    for (const detune of [-4, 4]) {
      const o = cc.createOscillator()
      o.type = 'sine'
      o.frequency.value = freq
      o.detune.value = detune
      o.connect(g)
      o.start()
      o.stop(cc.currentTime + dur + 0.1)
    }
  }

  function step() {
    if (state.stopped) return
    // a slow random walk, occasionally doubling at the fifth
    const root = SCALE[Math.floor(Math.random() * SCALE.length)]
    voice(root, 6 + Math.random() * 4)
    if (Math.random() < 0.45) {
      const other = SCALE[Math.floor(Math.random() * SCALE.length)]
      if (other !== root) setTimeout(() => voice(other, 5 + Math.random() * 3), 900)
    }
    state.timer = window.setTimeout(step, 3200 + Math.random() * 2600)
  }

  step()
}

export function stopMusic(): void {
  const c = audio()
  if (!bed) return
  const b = bed
  bed = null
  b.stopped = true
  clearTimeout(b.timer)
  if (c) {
    try {
      b.master.gain.cancelScheduledValues(c.currentTime)
      b.master.gain.setValueAtTime(b.master.gain.value, c.currentTime)
      b.master.gain.exponentialRampToValueAtTime(0.0001, c.currentTime + 1.2)
      setTimeout(() => { try { b.master.disconnect() } catch { /* already gone */ } }, 1500)
    } catch { /* context may be closed */ }
  }
}

export function musicPlaying(): boolean { return bed !== null }

/** Drop the bed while a listening clip plays, then bring it back. */
export function duckMusic(seconds: number): void {
  const c = audio()
  if (!bed || !c) return
  const g = bed.master.gain
  const now = c.currentTime
  const level = g.value
  try {
    g.cancelScheduledValues(now)
    g.setValueAtTime(level, now)
    g.exponentialRampToValueAtTime(Math.max(0.0001, level * 0.12), now + 0.25)
    g.exponentialRampToValueAtTime(level, now + seconds + 0.6)
  } catch { /* ignore */ }
}
